<a href="https://colab.research.google.com/github/aviv2525/Assignment2--lernning-flow/blob/main/Bitter_example_for_students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame, Series
from google.colab import files

In [25]:
uploaded = files.upload()
df = pd.read_csv('Bitter.csv')

Saving Bitter.csv to Bitter (1).csv

<ipython-input-25-97eaf8a239b0>:2: DtypeWarning: Columns (0,4,5,6,8,9,179,180,182,260,261,263,264,266,269,277,278,296) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Bitter.csv')

In [26]:
df.head()

,Index,Name,PUBCHEM_COMPOUND_CID,ACTIVITY,ID,NonBitterID,Smiles,Frequency,Canonical_Smiles,Standardize_Actions_Taken,...,Kappa_2_AM,Kappa_3,Kappa_3_AM,PHI,SC_0,SC_1,SC_2,SC_3_C,SC_3_CH,SC_3_P
0,1,7765,"7,765",Non-Bitter,NaN,1_Fnb,O(C([H])([H])C([H])([H])[H])C([H])(C([H])([H])...,1.0,CCOC(C)OCC,NaN,...,5.06450,5.00000,4.92000,5.01386,8.0,7.0,7.0,1.0,0.0,6.0
1,2,177,177,Non-Bitter,2_Fnb,2_Fnb,O=C([H])C([H])([H])[H],1.0,CC=O,NaN,...,1.67000,0.00000,0.00000,1.48630,3.0,2.0,1.0,0.0,0.0,0.0
2,3,62876,"62,876",Non-Bitter,3_Fnb,3_Fnb,O(C([H])(C([H])([H])[H])OC([H])([H])C([H])([H]...,1.0,CCCCOC(C)OCCc1ccccc1,StandardizeStereo\nStandardizeStereo_ChiralFlag,...,8.31033,7.05817,6.36993,6.85916,16.0,16.0,18.0,2.0,0.0,19.0
3,4,83036,"83,036",Non-Bitter,4_Fnb,4_Fnb,O(C([H])(C([H])([H])[H])OC([H])([H])C([H])([H]...,1.0,CC(C)CCOC(C)OCCC(C)C,NaN,...,8.24664,11.00000,10.92000,8.19952,14.0,13.0,15.0,3.0,0.0,12.0
4,5,108504,"108,504",Non-Bitter,5_Fnb,5_Fnb,O(C([H])([H])C([H])([H])C([H])=C([H])C([H])([H...,1.0,CCOC(C)OCCC=CCC,StandardizeStereo\nStandardizeStereo_ChiralFlag,...,8.75380,9.00000,8.65999,8.50578,12.0,11.0,11.0,1.0,0.0,10.0

In [27]:
df.dtypes

Index                    object
Name                     object
PUBCHEM_COMPOUND_CID     object
ACTIVITY                 object
ID                       object
                         ...
SC_1                    float64
SC_2                    float64
SC_3_C                  float64
SC_3_CH                 float64
SC_3_P                  float64
Length: 310, dtype: object

In [28]:
df_object=df.select_dtypes(include='object')

In [29]:
df_object

,Index,Name,PUBCHEM_COMPOUND_CID,ACTIVITY,ID,NonBitterID,Smiles,Canonical_Smiles,Standardize_Actions_Taken,Apol,...,E_ADJ_equ,E_ADJ_mag,E_DIST_equ,E_DIST_mag,V_ADJ_equ,V_ADJ_mag,V_DIST_equ,V_DIST_mag,Wiener,Zagreb
0,1,7765,"7,765",Non-Bitter,NaN,1_Fnb,O(C([H])([H])C([H])([H])[H])C([H])(C([H])([H])...,CCOC(C)OCC,NaN,"3,909.92",...,42.2929,53.303,115.927,255.094,48.5042,53.303,167.155,359.171,75,28
1,2,177,177,Non-Bitter,2_Fnb,2_Fnb,O=C([H])C([H])([H])[H],CC=O,NaN,"1,621.42",...,4,2,4,4,8.91968,8,13.7744,22.5,4,6
2,3,62876,"62,876",Non-Bitter,3_Fnb,3_Fnb,O(C([H])(C([H])([H])[H])OC([H])([H])C([H])([H]...,CCCCOC(C)OCCc1ccccc1,StandardizeStereo\nStandardizeStereo_ChiralFlag,"8,819.16",...,149.984,186.117,868.196,"1,953.86",139.152,160,891.406,"1,954.53",567,68
3,4,83036,"83,036",Non-Bitter,4_Fnb,4_Fnb,O(C([H])(C([H])([H])[H])OC([H])([H])C([H])([H]...,CC(C)CCOC(C)OCCC(C)C,NaN,"6,989.48",...,114.009,147.207,538.505,"1,185.94",110.675,122.211,652.831,"1,420.70",397,56
4,5,108504,"108,504",Non-Bitter,5_Fnb,5_Fnb,O(C([H])([H])C([H])([H])C([H])=C([H])C([H])([H...,CCOC(C)OCCC=CCC,StandardizeStereo\nStandardizeStereo_ChiralFlag,"6,277.60",...,82.7686,98.1075,375.982,788.964,88.8118,98.1075,468.196,976.917,265,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2070,NaN,NaN,"413,117",Bitter,NaN,NaN,NaN,NaN,NaN,"11,781.10",...,253.051,354.413,"1,400.39","3,732.69",193.859,226.477,"1,313.08","3,335.10",834,102
2071,NaN,NaN,"435,597",Bitter,NaN,NaN,NaN,NaN,NaN,"13,320.90",...,295.827,398.93,"1,918.65","5,107.06",232.192,268.078,"1,811.75","4,633.16","1,244",114
2072,NaN,NaN,"2,883,177",Bitter,NaN,NaN,NaN,NaN,NaN,"10,848.80",...,243.936,354.413,"1,139.41","3,349.80",181.343,212.877,"1,103.59","2,967.81",657,100
2073,NaN,NaN,"3,082,543",Bitter,NaN,NaN,NaN,NaN,NaN,"15,649.50",...,616.948,879.137,"5,249.55","14,713.10",404.411,474.842,"4,337.40","11,416","3,335",202
2074,NaN,(+/-) Equol,"91,469",Bitter,NaN,NaN,NaN,NaN,NaN,"10,291.60",...,233.696,325.212,"1,248.30","3,333.52",174.706,212.877,"1,052.42","2,596.25",623,96

In [30]:
df['ACTIVITY'].replace(['Bitter', 'Non-Bitter'], [int(1), int(0)], inplace=True)

<ipython-input-30-3f232ec570ae>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ACTIVITY'].replace(['Bitter', 'Non-Bitter'], [int(1), int(0)], inplace=True)
<ipython-input-30-3f232ec570ae>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['ACTIVITY'].replace(['Bitter', 'Non-Bitter'], [int(1), int(0)], inplace=True)

In [31]:
df.dtypes

Index                    object
Name                     object
PUBCHEM_COMPOUND_CID     object
ACTIVITY                  int64
ID                       object
                         ...
SC_1                    float64
SC_2                    float64
SC_3_C                  float64
SC_3_CH                 float64
SC_3_P                  float64
Length: 310, dtype: object

In [32]:
df=df.select_dtypes(exclude=['object'])

In [33]:
df.dtypes

ACTIVITY             int64
Frequency          float64
ALogP98            float64
ALogP98_Unknown    float64
ES_Sum_aaaC        float64
                    ...
SC_1               float64
SC_2               float64
SC_3_C             float64
SC_3_CH            float64
SC_3_P             float64
Length: 276, dtype: object

In [34]:
df.isnull().sum().sort_values(ascending=0)

Frequency          547
CHI_V_3_CH           1
CHI_V_2              1
CHI_V_1              1
CHI_V_0              1
                  ...
ES_Count_dS          0
ES_Count_dsCH        0
ES_Count_dSe         0
ES_Count_dsN         0
ES_Count_sssdAs      0
Length: 276, dtype: int64

In [35]:
ColumnsNames=df.columns.values
ColumnsNames

array(['ACTIVITY', 'Frequency', 'ALogP98', 'ALogP98_Unknown',
       'ES_Sum_aaaC', 'ES_Sum_aaCH', 'ES_Sum_aaN', 'ES_Sum_aaNH',
       'ES_Sum_aaO', 'ES_Sum_aaS', 'ES_Sum_aasC', 'ES_Sum_aaSe',
       'ES_Sum_aasN', 'ES_Sum_dCH2', 'ES_Sum_ddC', 'ES_Sum_ddsN',
       'ES_Sum_ddssS', 'ES_Sum_ddssSe', 'ES_Sum_dNH', 'ES_Sum_dO',
       'ES_Sum_dS', 'ES_Sum_dsCH', 'ES_Sum_dSe', 'ES_Sum_dsN',
       'ES_Sum_dssC', 'ES_Sum_dssS', 'ES_Sum_dssSe', 'ES_Sum_dsssP',
       'ES_Sum_sAsH2', 'ES_Sum_sBr', 'ES_Sum_sCH3', 'ES_Sum_sCl',
       'ES_Sum_sF', 'ES_Sum_sGeH3', 'ES_Sum_sI', 'ES_Sum_sLi',
       'ES_Sum_sNH2', 'ES_Sum_sNH3', 'ES_Sum_sOH', 'ES_Sum_sPbH3',
       'ES_Sum_sPH2', 'ES_Sum_ssAsH', 'ES_Sum_ssBe', 'ES_Sum_ssBH',
       'ES_Sum_ssCH2', 'ES_Sum_sSeH', 'ES_Sum_ssGeH2', 'ES_Sum_sSH',
       'ES_Sum_sSiH3', 'ES_Sum_ssNH', 'ES_Sum_ssNH2', 'ES_Sum_sSnH3',
       'ES_Sum_ssO', 'ES_Sum_ssPbH2', 'ES_Sum_ssPH', 'ES_Sum_ssS',
       'ES_Sum_sssAs', 'ES_Sum_sssB', 'ES_Sum_sssCH', 'ES_Sum_sssdAs',
       'ES_Sum_ssSe', 'ES_Sum_sssGeH', 'ES_Sum_ssSiH2', 'ES_Sum_sssN',
       'ES_Sum_sssNH', 'ES_Sum_ssSnH2', 'ES_Sum_sssP', 'ES_Sum_sssPbH',
       'ES_Sum_ssssB', 'ES_Sum_ssssBe', 'ES_Sum_ssssC', 'ES_Sum_ssssGe',
       'ES_Sum_sssSiH', 'ES_Sum_ssssN', 'ES_Sum_sssSnH', 'ES_Sum_ssssPb',
       'ES_Sum_sssssAs', 'ES_Sum_ssssSi', 'ES_Sum_ssssSn',
       'ES_Sum_sssssP', 'ES_Sum_tCH', 'ES_Sum_tN', 'ES_Sum_tsC',
       'ES_Count_aaaC', 'ES_Count_aaCH', 'ES_Count_aaN', 'ES_Count_aaNH',
       'ES_Count_aaO', 'ES_Count_aaS', 'ES_Count_aasC', 'ES_Count_aaSe',
       'ES_Count_aasN', 'ES_Count_dCH2', 'ES_Count_ddC', 'ES_Count_ddsN',
       'ES_Count_ddssS', 'ES_Count_ddssSe', 'ES_Count_dNH', 'ES_Count_dO',
       'ES_Count_dS', 'ES_Count_dsCH', 'ES_Count_dSe', 'ES_Count_dsN',
       'ES_Count_dssC', 'ES_Count_dssS', 'ES_Count_dssSe',
       'ES_Count_dsssP', 'ES_Count_sAsH2', 'ES_Count_sBr',
       'ES_Count_sCH3', 'ES_Count_sCl', 'ES_Count_sF', 'ES_Count_sGeH3',
       'ES_Count_sI', 'ES_Count_sLi', 'ES_Count_sNH2', 'ES_Count_sNH3',
       'ES_Count_sOH', 'ES_Count_sPbH3', 'ES_Count_sPH2',
       'ES_Count_ssAsH', 'ES_Count_ssBe', 'ES_Count_ssBH',
       'ES_Count_ssCH2', 'ES_Count_sSeH', 'ES_Count_ssGeH2',
       'ES_Count_sSH', 'ES_Count_sSiH3', 'ES_Count_ssNH',
       'ES_Count_ssNH2', 'ES_Count_sSnH3', 'ES_Count_ssO',
       'ES_Count_ssPbH2', 'ES_Count_ssPH', 'ES_Count_ssS',
       'ES_Count_sssAs', 'ES_Count_sssB', 'ES_Count_sssCH',
       'ES_Count_sssdAs', 'ES_Count_ssSe', 'ES_Count_sssGeH',
       'ES_Count_ssSiH2', 'ES_Count_sssN', 'ES_Count_sssNH',
       'ES_Count_ssSnH2', 'ES_Count_sssP', 'ES_Count_sssPbH',
       'ES_Count_ssssB', 'ES_Count_ssssBe', 'ES_Count_ssssC',
       'ES_Count_ssssGe', 'ES_Count_sssSiH', 'ES_Count_ssssN',
       'ES_Count_sssSnH', 'ES_Count_ssssPb', 'ES_Count_sssssAs',
       'ES_Count_ssssSi', 'ES_Count_ssssSn', 'ES_Count_sssssP',
       'ES_Count_tCH', 'ES_Count_tN', 'ES_Count_tsC', 'FormalCharge',
       'CoordDimension', 'IsChiral', 'HasGasteigerCharges', 'LogD',
       'Molecular_Solubility', 'HBA_Count', 'HBD_Count', 'NPlusO_Count',
       'Num_Atoms', 'Num_Bonds', 'Num_Hydrogens', 'Num_ExplicitHydrogens',
       'Num_ExplicitAtoms', 'Num_ExplicitBonds', 'Num_PositiveAtoms',
       'Num_NegativeAtoms', 'Num_SpiroAtoms', 'Num_BridgeHeadAtoms',
       'Num_RingBonds', 'Num_RotatableBonds', 'Num_AromaticBonds',
       'Num_BridgeBonds', 'Num_Rings', 'Num_AromaticRings',
       'Num_RingAssemblies', 'Num_Rings3', 'Num_Rings4', 'Num_Rings5',
       'Num_Rings6', 'Num_Rings7', 'Num_Rings8', 'Num_Rings9Plus',
       'Num_Chains', 'Num_ChainAssemblies', 'Num_Fragments',
       'Num_ComplexedFragments', 'Num_MetalAtoms', 'Num_SGroups',
       'Num_Superatoms', 'Num_Isotopes', 'Num_CustomData', 'Num_PiBonds',
       'Num_RepeatUnits', 'Num_V3000Templates', 'Num_RGroupFragments',
       'Num_StereoAtoms', 'Num_StereoBonds', 'Num_SingleBonds',
       'Num_DoubleBonds', 'Num_TripleBonds', 'Num_AliphaticSingleBonds',
       'Num_AliphaticDoubleBonds', 'Num_UnknownStereoAtoms',
       'Num_UnknownStereoBonds', 'Num_DativeBonds', 'Num_HydrogenBonds',
       'Num_AlleneStereoCenters', 'Num_AtropisomerCenters',
       'Num_AxialStereoCenters', 'Num_TrueAlleneStereoCenters',
       'Num_TrueAtropisomerCenters', 'Num_AtomClasses',
       'Num_Macro_Chains', 'Num_Macro_Residues', 'Num_TerminalRotomers',
       'Num_TrueStereoAtoms', 'Num_UnknownTrueStereoAtoms',
       'Num_PseudoStereoAtoms', 'Num_UnknownPseudoStereoAtoms',
       'Num_MesoStereoAtoms', 'Num_EnhancedStereoAtoms', 'Num_QueryAtoms',
       'Num_QueryBonds', 'Num_H_Acceptors', 'Num_H_Donors',
       'Num_H_Acceptors_Lipinski', 'Num_H_Donors_Lipinski',
       'Organic_Count', 'Molecular_FractionalPolarSurfaceArea',
       'Molecular_FractionalPolarSASA', 'BIC', 'CIC', 'IAC_Mean',
       'IAC_Total', 'IC', 'SIC', 'CHI_0', 'CHI_1', 'CHI_2', 'CHI_3_C',
       'CHI_3_CH', 'CHI_3_P', 'CHI_V_0', 'CHI_V_1', 'CHI_V_2',
       'CHI_V_3_C', 'CHI_V_3_CH', 'CHI_V_3_P', 'JX', 'JY', 'Kappa_1',
       'Kappa_1_AM', 'Kappa_2', 'Kappa_2_AM', 'Kappa_3', 'Kappa_3_AM',
       'PHI', 'SC_0', 'SC_1', 'SC_2', 'SC_3_C', 'SC_3_CH', 'SC_3_P'],
      dtype=object)

In [36]:
df.nunique()

ACTIVITY              2
Frequency             1
ALogP98            1635
ALogP98_Unknown       3
ES_Sum_aaaC          58
                   ...
SC_1                 57
SC_2                 83
SC_3_C               36
SC_3_CH               3
SC_3_P              113
Length: 276, dtype: int64

In [37]:
df.columns[df.nunique(dropna=True)<=1]

Index(['Frequency', 'ES_Sum_aaSe', 'ES_Sum_ddssSe', 'ES_Sum_dSe',
       'ES_Sum_dssSe', 'ES_Sum_sAsH2', 'ES_Sum_sGeH3', 'ES_Sum_sLi',
       'ES_Sum_sPbH3', 'ES_Sum_sPH2', 'ES_Sum_ssAsH', 'ES_Sum_ssBe',
       'ES_Sum_ssBH', 'ES_Sum_sSeH', 'ES_Sum_ssGeH2', 'ES_Sum_sSiH3',
       'ES_Sum_sSnH3', 'ES_Sum_ssPbH2', 'ES_Sum_ssPH', 'ES_Sum_sssAs',
       'ES_Sum_sssB', 'ES_Sum_sssdAs', 'ES_Sum_ssSe', 'ES_Sum_sssGeH',
       'ES_Sum_ssSiH2', 'ES_Sum_ssSnH2', 'ES_Sum_sssP', 'ES_Sum_sssPbH',
       'ES_Sum_ssssB', 'ES_Sum_ssssBe', 'ES_Sum_ssssGe', 'ES_Sum_sssSiH',
       'ES_Sum_sssSnH', 'ES_Sum_ssssPb', 'ES_Sum_sssssAs', 'ES_Sum_ssssSi',
       'ES_Sum_ssssSn', 'ES_Sum_sssssP', 'ES_Count_aaSe', 'ES_Count_ddssSe',
       'ES_Count_dSe', 'ES_Count_dssSe', 'ES_Count_sAsH2', 'ES_Count_sGeH3',
       'ES_Count_sLi', 'ES_Count_sPbH3', 'ES_Count_sPH2', 'ES_Count_ssAsH',
       'ES_Count_ssBe', 'ES_Count_ssBH', 'ES_Count_sSeH', 'ES_Count_ssGeH2',
       'ES_Count_sSiH3', 'ES_Count_sSnH3', 'ES_Count_ssPbH2', 'ES_Count_ssPH',
       'ES_Count_sssAs', 'ES_Count_sssB', 'ES_Count_sssdAs', 'ES_Count_ssSe',
       'ES_Count_sssGeH', 'ES_Count_ssSiH2', 'ES_Count_ssSnH2',
       'ES_Count_sssP', 'ES_Count_sssPbH', 'ES_Count_ssssB', 'ES_Count_ssssBe',
       'ES_Count_ssssGe', 'ES_Count_sssSiH', 'ES_Count_sssSnH',
       'ES_Count_ssssPb', 'ES_Count_sssssAs', 'ES_Count_ssssSi',
       'ES_Count_ssssSn', 'ES_Count_sssssP', 'HasGasteigerCharges',
       'Num_MetalAtoms', 'Num_SGroups', 'Num_Superatoms', 'Num_CustomData',
       'Num_PiBonds', 'Num_RepeatUnits', 'Num_V3000Templates',
       'Num_RGroupFragments', 'Num_DativeBonds', 'Num_HydrogenBonds',
       'Num_AlleneStereoCenters', 'Num_AtropisomerCenters',
       'Num_AxialStereoCenters', 'Num_TrueAlleneStereoCenters',
       'Num_Macro_Chains', 'Num_Macro_Residues', 'Num_PseudoStereoAtoms',
       'Num_EnhancedStereoAtoms', 'Num_QueryAtoms', 'Num_QueryBonds'],
      dtype='object')

In [38]:
to_drop=df.columns[df.nunique(dropna=True)<=1]

In [39]:
df.drop(to_drop, inplace=True, axis=1)

In [40]:
df.shape

(2075, 180)

In [47]:
df = df.dropna(axis=1)

In [48]:
df.shape

(2075, 145)

In [53]:
df = df.loc[:, df.nunique() > 1]

In [54]:
df.shape

(2075, 145)

In [55]:
threshold = len(df) * 0.5
df = df.drop(columns=[col for col in df.columns if (df[col] == 0).sum() > threshold])

In [56]:
df.shape

(2075, 38)

In [57]:
import numpy as np

# חישוב מטריצת המתאם
corr_matrix = df.corr().abs()

# יצירת מסכה לחלק העליון של המטריצה
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# זיהוי עמודות עם מתאם גבוה (למשל, מעל 0.9)
to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]

# הסרת עמודות עם מתאם גבוה
df.drop(columns=to_drop, inplace=True)

In [59]:
df.shape

(2075, 21)

In [63]:
import pandas as pd

# חישוב ממוצע וסטיית תקן לכל משתנה
mean_std = df.describe().loc[['mean', 'std']]
print(mean_std)

      ES_Sum_dO  ES_Sum_dssC  ES_Sum_sCH3  ES_Sum_ssCH2  ES_Count_dssC  \
mean  11.697615    -0.070974     3.551013      2.671289       1.118554
std   16.724731     1.494896     2.877235      3.825973       1.470185

      ES_Count_ssCH2  CoordDimension      LogD  Molecular_Solubility  \
mean        3.063133        2.056386  1.970725             -2.741884
std         3.426648        0.230720  1.992589              1.884917

      HBA_Count  ...  Num_Atoms  Num_Hydrogens  Num_RingBonds  \
mean   1.766747  ...  14.301205      16.312771       6.172530
std    1.733318  ...   9.390149      10.055631       6.852849

      Num_RotatableBonds  Num_RingAssemblies  Num_Rings6  Num_Fragments  \
mean            4.213976            0.826988    0.824096       0.999518
std             4.490588            0.793807    1.081268       0.021953

      Num_DoubleBonds  Num_AliphaticDoubleBonds  \
mean         3.153253                  1.515663
std          2.764047                  1.521026

      Molecular_FractionalPolarSurfaceArea
mean                              0.227157
std                               0.150682

[2 rows x 21 columns]

In [66]:
print(df.columns)

Index(['ES_Sum_dO', 'ES_Sum_dssC', 'ES_Sum_sCH3', 'ES_Sum_ssCH2',
       'ES_Count_dssC', 'ES_Count_ssCH2', 'CoordDimension', 'LogD',
       'Molecular_Solubility', 'HBA_Count', 'NPlusO_Count', 'Num_Atoms',
       'Num_Hydrogens', 'Num_RingBonds', 'Num_RotatableBonds',
       'Num_RingAssemblies', 'Num_Rings6', 'Num_Fragments', 'Num_DoubleBonds',
       'Num_AliphaticDoubleBonds', 'Molecular_FractionalPolarSurfaceArea'],
      dtype='object')

In [68]:
print(df.head())

   ES_Sum_dO  ES_Sum_dssC  ES_Sum_sCH3  ES_Sum_ssCH2  ES_Count_dssC  \
0      0.000          0.0        5.803         1.446              0
1      8.805          0.0        1.444         0.000              0
2      0.000          0.0        4.116         4.727              0
3      0.000          0.0       10.781         3.830              0
4      0.000          0.0        6.017         3.537              0

   ES_Count_ssCH2  CoordDimension   LogD  Molecular_Solubility  HBA_Count  \
0               2               3  0.777                -0.883          2
1               0               2 -0.183                 0.168          1
2               5               2  3.313                -4.081          2
3               4               2  3.240                -3.227          2
4               4               2  2.225                -2.739          2

   ...  Num_Atoms  Num_Hydrogens  Num_RingBonds  Num_RotatableBonds  \
0  ...          8             14              0                   4
1  ...          3              4              0                   0
2  ...         16             22              6                   8
3  ...         14             26              0                   8
4  ...         12             20              0                   7

   Num_RingAssemblies  Num_Rings6  Num_Fragments  Num_DoubleBonds  \
0                   0           0              1                0
1                   0           0              1                1
2                   1           1              1                3
3                   0           0              1                0
4                   0           0              1                1

   Num_AliphaticDoubleBonds  Molecular_FractionalPolarSurfaceArea
0                         0                                 0.126
1                         1                                 0.286
2                         0                                 0.075
3                         0                                 0.075
4                         1                                 0.089

[5 rows x 21 columns]

In [73]:
# חיפוש עמודות עם ערכים טקסטואליים
text_columns = df.select_dtypes(include='object').columns
print(text_columns)

Index([], dtype='object')